# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68da9591c07df16899be4d6644177d5454cebb379efbb0db1cb598b4b33416028f1231e61fea298852bdbeda838ee6ffbf8b1cf5f780aed0067ab60a0df2f537

test:
  secret_key_base: 9ca9d5dcb66cb08434e4299fa2f7f4c78d4da5050fb441175a8846eaa5446cd628d6e7d3f59f9ea966b5f980826d5448dda23d68bda46228b0920352d32b532a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
